

package ws.billy.CookieGadgets.utils;

import ws.billy.CookieGadgets.CookieGadgets;
import ws.billy.CookieGadgets.configuration.FileManager;

public enum MessageType
{
    CHECKING_FOR_UPDATE("CHECKING_FOR_UPDATE", 0, "{PREFIX}&rChecking for updates...", "Checking-For-Update"), 
    CONNECTING_TO_DATABASE("CONNECTING_TO_DATABASE", 1, "Connecting to {DATABASE} database...", (String)null), 
    COOLDOWN("COOLDOWN", 2, "{PREFIX}&cYou must wait &b{COOLDOWN}s &cbefore using this!", "Cooldown"), 
    DATABASE_CONNECTION_IS_CLOSED("DATABASE_CONNECTION_IS_CLOSED", 3, "{DATABASE} database connection has been closed.", (String)null), 
    DATABASE_RECONNECTION_IS_TOO_FREQUENT("DATABASE_RECONNECTION_IS_TOO_FREQUENT", 4, "The number of reconnections to {DATABASE} database is too frequent. Please contact the author for help.", (String)null), 
    ERROR("ERROR", 5, "{PREFIX}&cAn error occurred while performing this operation!", "Error"), 
    FAILED_TO_CLOSE_THE_DATEBASE("FAILED_TO_CLOSE_THE_DATEBASE", 6, "Failed to close {DATABASE} database connection!", (String)null), 
    FAILED_TO_CONNECT_TO_DATEBASE("FAILED_TO_CONNECT_TO_DATEBASE", 7, "Failed to connect to {DATABASE} database!", (String)null), 
    GIVE_MENU_ITEM("GIVE_MENU_ITEM", 8, "{PREFIX}&aYou've successfully gave a menu selector to &b{PLAYER}&a.", (String)null), 
    NOT_ALLOWED_FROM_COMMAND_SENDER("NOT_ALLOWED_FROM_COMMAND_SENDER", 9, "{PREFIX}&cYou're not allowed to execute this command thru this command sender.", (String)null), 
    NO_PERMISSION("NO_PERMISSION", 10, "{PREFIX}&cYou don't have the required permission {PERMISSION}!", "No-Permission"), 
    NO_PERMISSION_FOR_MENU_ITEM("NO_PERMISSION_FOR_MENU_ITEM", 11, "{PREFIX}&c{PLAYER} &cdoes not have permission for menu selector. You need to give him 'CookieGadgets.menuselector' permission before he can receive the menu selector.", (String)null),
    NO_PERMISSION_FOR_MENU_ITEM_IN_THAT_WORLD("NO_PERMISSION_FOR_MENU_ITEM_IN_THAT_WORLD", 12, "{PREFIX}&c{PLAYER} &cmust stay at the world which CookieGadgets is enabled before he can receive menu selector.", (String)null),
    PLAYER_RECEIVE_MENU_ITEM("PLAYER_RECEIVE_MENU_ITEM", 13, "{PREFIX}&eA menu selector has been added into your inventory!", (String)null), 
    SUCCESSFULLY_CONNECTED_TO_DATABASE("SUCCESSFULLY_CONNECTED_TO_DATABASE", 14, "Successfully connected to {DATABASE} database.", (String)null), 
    WORLD_DISABLED("WORLD_DISABLED", 15, "{PREFIX}&cYou don't have permission to do that in this world!", "World-Disabled"), 
    PARTICLE_EFFECT_NOT_SUPPORTED("PARTICLE_EFFECT_NOT_SUPPORTED", 16, "Effect {PARTICLE} doesn't support on your server!", (String)null), 
    BANNERS_ARE_DISABLED("BANNERS_ARE_DISABLED", 17, "{PREFIX}&cCosmetic banners are disabled!", "Banners-Are-Disabled"), 
    CLOAKS_ARE_DISABLED("CLOAKS_ARE_DISABLED", 18, "{PREFIX}&cCosmetic cloaks are disabled!", "Cloaks-Are-Disabled"), 
    EMOTES_ARE_DISABLED("EMOTES_ARE_DISABLED", 19, "{PREFIX}&cCosmetic emotes are disabled!", "Emotes-Are-Disabled"), 
    GADGETS_ARE_DISABLED("GADGETS_ARE_DISABLED", 20, "{PREFIX}&cCosmetic gadgets are disabled!", "Gadgets-Are-Disabled"), 
    HATS_ARE_DISABLED("HATS_ARE_DISABLED", 21, "{PREFIX}&cCosmetic hats are disabled!", "Hats-Are-Disabled"), 
    ANIMATED_HATS_ARE_DISABLED("ANIMATED_HATS_ARE_DISABLED", 22, "{PREFIX}&cCosmetic animated hats are disabled!", "Animated-Hats-Are-Disabled"), 
    MORPHS_ARE_DISABLED("MORPHS_ARE_DISABLED", 23, "{PREFIX}&cCosmetic morphs are disabled!", "Morphs-Are-Disabled"), 
    PARTICLES_ARE_DISABLED("PARTICLES_ARE_DISABLED", 24, "{PREFIX}&cCosmetic particles are disabled!", "Particles-Are-Disabled"), 
    PETS_ARE_DISABLED("PETS_ARE_DISABLED", 25, "{PREFIX}&cCosmetic pets are disabled!", "Pets-Are-Disabled"), 
    MINIATURES_ARE_DISABLED("MINIATURES_ARE_DISABLED", 26, "{PREFIX}&cCosmetic miniatures are disabled!", "Miniatures-Are-Disabled"), 
    SUITS_ARE_DISABLED("SUITS_ARE_DISABLED", 27, "{PREFIX}&cCosmetic suits are disabled!", "Suits-Are-Disabled"), 
    EQUIP_ANIMATED_HAT_FOR_PLAYER("EQUIP_ANIMATED_HAT_FOR_PLAYER", 28, "&eYou equipped {ANIMATED_HAT} for &b{PLAYER}&e.", "Equip-Animated-Hat-For-Player"), 
    EQUIP_BANNER_FOR_PLAYER("EQUIP_BANNER_FOR_PLAYER", 29, "&eYou equipped {BANNER} for &b{PLAYER}&e.", "Equip-Banner-For-Player"), 
    EQUIP_CLOAK_FOR_PLAYER("EQUIP_CLOAK_FOR_PLAYER", 30, "&eYou equipped {CLOAK} for &b{PLAYER}&e.", "Equip-Cloak-For-Player"), 
    EQUIP_EMOTE_FOR_PLAYER("EQUIP_EMOTE_FOR_PLAYER", 31, "&eYou equipped {EMOTE} for &b{PLAYER}&e.", "Equip-Emote-For-Player"), 
    EQUIP_GADGET_FOR_PLAYER("EQUIP_GADGET_FOR_PLAYER", 32, "&eYou equipped {GADGET} for &b{PLAYER}&e.", "Equip-Gadget-For-Player"), 
    EQUIP_HAT_FOR_PLAYER("EQUIP_HAT_FOR_PLAYER", 33, "&eYou equipped {HAT} for &b{PLAYER}&e.", "Equip-Hat-For-Player"), 
    EQUIP_MINIATURE_FOR_PLAYER("EQUIP_MINIATURE_FOR_PLAYER", 34, "&eSpawned {MINIATURE} for &b{PLAYER}.", "Equip-Miniature-For-Player"), 
    EQUIP_MORPH_FOR_PLAYER("EQUIP_MORPH_FOR_PLAYER", 35, "&eYou morphed for &b{PLAYER} &eas a {MORPH}&e.", "Equip-Morph-For-Player"), 
    EQUIP_PARTICLE_FOR_PLAYER("EQUIP_PARTICLE_FOR_PLAYER", 36, "&eYou equipped {PARTICLE} for &b{PLAYER}&e.", "Equip-Particle-For-Player"), 
    EQUIP_PET_FOR_PLAYER("EQUIP_PET_FOR_PLAYER", 37, "&eSpawned {PET} &epet for &b{PLAYER}.", "Equip-Pet-For-Player"), 
    EQUIP_SUIT_FOR_PLAYER("EQUIP_SUIT_FOR_PLAYER", 38, "&eYou equipped {SUIT} for &b{PLAYER}&e.", "Equip-Suit-For-Player"), 
    SELECT_ANIMATED_HAT("SELECT_ANIMATED_HAT", 39, "&aYou selected &e{ANIMATED_HAT}&a.", "Select-Animated-Hat"), 
    SELECT_BANNER("SELECT_BANNER", 40, "&aYou selected &e{BANNER}&a.", "Select-Banner"), 
    SELECT_CLOAK("SELECT_CLOAK", 41, "&aYou selected &e{CLOAK}&a.", "Select-Cloak"), 
    SELECT_EMOTE("SELECT_EMOTE", 42, "&aYou selected &e{EMOTE}&a.", "Select-Emote"), 
    SELECT_GADGET("SELECT_GADGET", 43, "&aYou selected &e{GADGET}&a.", "Select-Gadget"), 
    SELECT_HAT("SELECT_HAT", 44, "&aYou selected &e{HAT}&a.", "Select-Hat"), 
    SELECT_MINIATURE("SELECT_MINIATURE", 45, "&aSpawned your &e{MINIATURE}&a.", "Select-Miniature"), 
    SELECT_MORPH("SELECT_MORPH", 46, "&aYou are now morphed as a &e{MORPH}&a.", "Select-Morph"), 
    SELECT_PARTICLE("SELECT_PARTICLE", 47, "&aYou selected &e{PARTICLE}&a.", "Select-Particle"), 
    SELECT_PET("SELECT_PET", 48, "&aSpawned your &e{PET} &apet.", "Select-Pet"), 
    SELECT_SUIT("SELECT_SUIT", 49, "&aYou selected &e{SUIT}&a.", "Select-Suit"), 
    SELECT_ENTIRE_SUIT("SELECT_ENTIRE_SUIT", 50, "&aYou equipped {PIECES} piece(s) of the &e{SUIT}&a.", "Select-Entire-Suit"), 
    NO_SUIT_PIECES_TO_EQUIP("NO_SUIT_PIECES_TO_EQUIP", 51, "&cYou don't have any pieces of suit to equip!", "No-Suit-Pieces-To-Equip"), 
    RESET_COSMETICS("RESET_COSMETICS", 52, "&aReset active Cosmetics.", "Reset-Cosmetics"), 
    RESET_COMPLETED("RESET_COMPLETED", 53, "&aCosmetic reset completed.", (String)null), 
    RESET_ANIMATED_HAT("RESET_ANIMATED_HAT", 54, "&aReset your animated Hat.", "Reset-Animated-Hat"), 
    RESET_BANNER("RESET_BANNER", 55, "&aReset your Banner.", "Reset-Banner"), 
    RESET_CLOAK("RESET_CLOAK", 56, "&aReset your Cloak.", "Reset-Cloak"), 
    RESET_EMOTE("RESET_EMOTE", 57, "&aReset your Emote.", "Reset-Emote"), 
    RESET_GADGET("RESET_GADGET", 58, "&aReset your Gadget.", "Reset-Gadget"), 
    RESET_HAT("RESET_HAT", 59, "&aReset your Hat.", "Reset-Hat"), 
    RESET_MINIATURE("RESET_MINIATURE", 60, "&aDespawned your miniature.", "Reset-Miniature"), 
    RESET_MORPH("RESET_MORPH", 61, "&aReset your Morph.", "Reset-Morph"), 
    RESET_PARTICLE("RESET_PARTICLE", 62, "&aReset your Particle.", "Reset-Particle"), 
    RESET_PET("RESET_PET", 63, "&aDespawned your Pet.", "Reset-Pet"), 
    RESET_SUIT("RESET_SUIT", 64, "&aReset your Suit.", "Reset-Suit"), 
    RESET_SUIT_HELMET("RESET_SUIT_HELMET", 65, "&aReset your Helmet.", "Reset-Suit-Helmet"), 
    RESET_SUIT_CHESTPLATE("RESET_SUIT_CHESTPLATE", 66, "&aReset your Chestplate.", "Reset-Suit-Chestplate"), 
    RESET_SUIT_LEGGINGS("RESET_SUIT_LEGGINGS", 67, "&aReset your Leggings.", "Reset-Suit-Leggings"), 
    RESET_SUIT_BOOTS("RESET_SUIT_BOOTS", 68, "&aReset your Boots.", "Reset-Suit-Boots"), 
    GRANTED_ACCESS_TO_ANIMATED_HAT("GRANTED_ACCESS_TO_ANIMATED_HAT", 69, "&eYou've been granted permission to equip {ANIMATED_HAT}&e.", "Granted-Access-To-Animated-Hat"), 
    GRANTED_ACCESS_TO_BANNER("GRANTED_ACCESS_TO_BANNER", 70, "&eYou've been granted permission to equip {BANNER}&e.", "Granted-Access-To-Banner"), 
    GRANTED_ACCESS_TO_CLOAK("GRANTED_ACCESS_TO_CLOAK", 71, "&eYou've been granted permission to equip {CLOAK}&e.", "Granted-Access-To-Cloak"), 
    GRANTED_ACCESS_TO_EMOTE("GRANTED_ACCESS_TO_EMOTE", 72, "&eYou've been granted permission to equip {EMOTE}&e.", "Granted-Access-To-Emote"), 
    GRANTED_ACCESS_TO_GADGET("GRANTED_ACCESS_TO_GADGET", 73, "&eYou've been granted permission to equip {GADGET}&e.", "Granted-Access-To-Gadget"), 
    GRANTED_ACCESS_TO_HAT("GRANTED_ACCESS_TO_HAT", 74, "&eYou've been granted permission to equip {HAT}&e.", "Granted-Access-To-Hat"), 
    GRANTED_ACCESS_TO_MINIATURE("GRANTED_ACCESS_TO_MINIATURE", 75, "&eYou've been granted permission to equip {MINIATURE}&e.", "Granted-Access-To-Miniature"), 
    GRANTED_ACCESS_TO_MORPH("GRANTED_ACCESS_TO_MORPH", 76, "&eYou've been granted permission to equip {MORPH}&e.", "Granted-Access-To-Morph"), 
    GRANTED_ACCESS_TO_PARTICLE("GRANTED_ACCESS_TO_PARTICLE", 77, "&eYou've been granted permission to equip {PARTICLE}&e.", "Granted-Access-To-Particle"), 
    GRANTED_ACCESS_TO_PET("GRANTED_ACCESS_TO_PET", 78, "&eYou've been granted permission to equip {PET}&e.", "Granted-Access-To-Pet"), 
    GRANTED_ACCESS_TO_SUIT("GRANTED_ACCESS_TO_SUIT", 79, "&eYou've been granted permission to equip {SUIT}&e.", "Granted-Access-To-Suit"), 
    GRANTED_ACCESS_TO_ANIMATED_HAT_FOR_PLAYER("GRANTED_ACCESS_TO_ANIMATED_HAT_FOR_PLAYER", 80, "&e{PLAYER} is now allowed to use {ANIMATED_HAT}&e.", "Granted-Access-To-Animated-Hat-For-Player"), 
    GRANTED_ACCESS_TO_BANNER_FOR_PLAYER("GRANTED_ACCESS_TO_BANNER_FOR_PLAYER", 81, "&e{PLAYER} is now allowed to use {BANNER}&e.", "Granted-Access-To-Banner-For-Player"), 
    GRANTED_ACCESS_TO_CLOAK_FOR_PLAYER("GRANTED_ACCESS_TO_CLOAK_FOR_PLAYER", 82, "&e{PLAYER} is now allowed to use {CLOAK}&e.", "Granted-Access-To-Cloak-For-Player"), 
    GRANTED_ACCESS_TO_EMOTE_FOR_PLAYER("GRANTED_ACCESS_TO_EMOTE_FOR_PLAYER", 83, "&e{PLAYER} is now allowed to use {EMOTE}&e.", "Granted-Access-To-Emote-For-Player"), 
    GRANTED_ACCESS_TO_GADGET_FOR_PLAYER("GRANTED_ACCESS_TO_GADGET_FOR_PLAYER", 84, "&e{PLAYER} is now allowed to use {GADGET}&e.", "Granted-Access-To-Gadget-For-Player"), 
    GRANTED_ACCESS_TO_HAT_FOR_PLAYER("GRANTED_ACCESS_TO_HAT_FOR_PLAYER", 85, "&e{PLAYER} is now allowed to use {HAT}&e.", "Granted-Access-To-Hat-For-Player"), 
    GRANTED_ACCESS_TO_MINIATURE_FOR_PLAYER("GRANTED_ACCESS_TO_MINIATURE_FOR_PLAYER", 86, "&e{PLAYER} is now allowed to use {MINIATURE}&e.", "Granted-Access-To-Miniature-For-Player"), 
    GRANTED_ACCESS_TO_MORPH_FOR_PLAYER("GRANTED_ACCESS_TO_MORPH_FOR_PLAYER", 87, "&e{PLAYER} is now allowed to use {MORPH}&e.", "Granted-Access-To-Morph-For-Player"), 
    GRANTED_ACCESS_TO_PARTICLE_FOR_PLAYER("GRANTED_ACCESS_TO_PARTICLE_FOR_PLAYER", 88, "&e{PLAYER} is now allowed to use {PARTICLE}&e.", "Granted-Access-To-Particle-For-Player"), 
    GRANTED_ACCESS_TO_PET_FOR_PLAYER("GRANTED_ACCESS_TO_PET_FOR_PLAYER", 89, "&e{PLAYER} is now allowed to use {PET}&e.", "Granted-Access-To-Pet-For-Player"), 
    GRANTED_ACCESS_TO_SUIT_FOR_PLAYER("GRANTED_ACCESS_TO_SUIT_FOR_PLAYER", 90, "&e{PLAYER} is now allowed to use {SUIT}&e.", "Granted-Access-To-Suit-For-Player"), 
    NO_LONGER_HAVE_ACCESS_TO_ANIMATED_HAT("NO_LONGER_HAVE_ACCESS_TO_ANIMATED_HAT", 91, "&eYou no longer have access to {ANIMATED_HAT}&e.", "No-Longer-Have-Access-To-Animated-Hat"), 
    NO_LONGER_HAVE_ACCESS_TO_BANNER("NO_LONGER_HAVE_ACCESS_TO_BANNER", 92, "&eYou no longer have access to {BANNER}&e.", "No-Longer-Have-Access-To-Banner"), 
    NO_LONGER_HAVE_ACCESS_TO_CLOAK("NO_LONGER_HAVE_ACCESS_TO_CLOAK", 93, "&eYou no longer have access to {CLOAK}&e.", "No-Longer-Have-Access-To-Cloak"), 
    NO_LONGER_HAVE_ACCESS_TO_EMOTE("NO_LONGER_HAVE_ACCESS_TO_EMOTE", 94, "&eYou no longer have access to {EMOTE}&e.", "No-Longer-Have-Access-To-Emote"), 
    NO_LONGER_HAVE_ACCESS_TO_GADGET("NO_LONGER_HAVE_ACCESS_TO_GADGET", 95, "&eYou no longer have access to {GADGET}&e.", "No-Longer-Have-Access-To-Gadget"), 
    NO_LONGER_HAVE_ACCESS_TO_HAT("NO_LONGER_HAVE_ACCESS_TO_HAT", 96, "&eYou no longer have access to {HAT}&e.", "No-Longer-Have-Access-To-Hat"), 
    NO_LONGER_HAVE_ACCESS_TO_MINIATURE("NO_LONGER_HAVE_ACCESS_TO_MINIATURE", 97, "&eYou no longer have access to {MINIATURE}&e.", "No-Longer-Have-Access-To-Miniature"), 
    NO_LONGER_HAVE_ACCESS_TO_MORPH("NO_LONGER_HAVE_ACCESS_TO_MORPH", 98, "&eYou no longer have access to {MORPH}&e.", "No-Longer-Have-Access-To-Morph"), 
    NO_LONGER_HAVE_ACCESS_TO_PARTICLE("NO_LONGER_HAVE_ACCESS_TO_PARTICLE", 99, "&eYou no longer have access to {PARTICLE}&e.", "No-Longer-Have-Access-To-Particle"), 
    NO_LONGER_HAVE_ACCESS_TO_PET("NO_LONGER_HAVE_ACCESS_TO_PET", 100, "&eYou no longer have access to {PET}&e.", "No-Longer-Have-Access-To-Pet"), 
    NO_LONGER_HAVE_ACCESS_TO_SUIT("NO_LONGER_HAVE_ACCESS_TO_SUIT", 101, "&eYou no longer have access to {SUIT}&e.", "No-Longer-Have-Access-To-Suit"), 
    ALREADY_HAS_PERMISSION("ALREADY_HAS_PERMISSION", 102, "&c{PLAYER} already has this permission.", "Already-Has-Permission"), 
    SUCCESSFUL_REMOVE_PERMISSION("SUCCESSFUL_REMOVE_PERMISSION", 103, "&eSuccessful remove the permission to access &c{TYPE} &efrom {PLAYER}&e.", "Successful-Remove-Permission"), 
    CHARACTERS_TOO_LONG("CHARACTERS_TOO_LONG", 104, "{PREFIX}&cThe pet's name cannot be longer than {CHARACTERS} characters!", "Characters-Too-Long"), 
    DOES_NOT_SUPPORT_CHARACTERS("DOES_NOT_SUPPORT_CHARACTERS", 105, "{PREFIX}&cYou can only use English alphabet for the name.", "Does-Not-Support-Characters"), 
    NO_PLAYER_NEARBY("NO_PLAYER_NEARBY", 106, "{PREFIX}&cThere aren't any players nearby!", "No-Player-Nearby"), 
    NOT_ALLOWED_FROM_CONSOLE("NOT_ALLOWED_FROM_CONSOLE", 107, "{PREFIX}&cYou cannot use this command from console!", "Not-Allowed-From-Console"), 
    NOT_ALLOWED_COSMETICS_IN_THIS_LOCATION("NOT_ALLOWED_COSMETICS_IN_THIS_LOCATION", 108, "{PREFIX}&cYou're not allowed to use cosmetics in this location!", "Not-Allow-Cosmetics-In-This-Location"), 
    NOT_ALLOWED_TELEPORT_TO_THAT_LOCATION("NOT_ALLOWED_TELEPORT_TO_THAT_LOCATION", 109, "{PREFIX}&cYou're not allowed to teleport to that location!", "Not-Allow-Teleport-To-That-Location"), 
    NOT_ENOUGH_SPACE("NOT_ENOUGH_SPACE", 110, "{PREFIX}&cNot enough space around you or above you to use this gadget!", "Not-Enough-Space"), 
    NOT_ENOUGH_SPACE_FOR_TARGET_BLOCK("NOT_ENOUGH_SPACE_FOR_TARGET_BLOCK", 111, "{PREFIX}&cThere is not enough space to use this gadget on the block you targeted!", "Not-Enough-Space-For-Target-Block"), 
    NOT_ON_GROUND("NOT_ON_GROUND", 112, "{PREFIX}&cYou must be on the ground to use this!", "Not-On-Ground"), 
    NOT_ON_FLAT_GROUND("NOT_ON_FLAT_GROUND", 113, "{PREFIX}&cYou must be on the flat ground to use this!", "Not-On-Flat-Ground"), 
    STAND_ON_TWO_BLOCKS_HIGH("STAND_ON_TWO_BLOCKS_HIGH", 114, "{PREFIX}&cYou must stand on higher than two blocks high of solid block!", "Stand-On-Two-Blocks-High"), 
    PLAYER_NOT_FOUND("PLAYER_NOT_FOUND", 115, "{PREFIX}&cPlayer not found!", "Player-Not-Found"), 
    PLAYER_IS_OFFLINE("PLAYER_IS_OFFLINE", 116, "{PREFIX}&cThis player is currently offline!", "Player-Is-Offline"), 
    RELOADED_PLUGIN("RELOADED_PLUGIN", 117, "{PREFIX}&3CookieGadgets plugin has been reloaded.", "Plugin-Reloaded"),
    RELOADING_PLUGIN("RELOADING_PLUGIN", 118, "{PREFIX}&3Reloading plugin...", "Reloading-Plugin"), 
    REQUIRED_NUMBER_FORMAT("REQUIRED_NUMBER_FORMAT", 119, "{PREFIX}&cA number is required!", "Required-Number-Format"), 
    REQUIRED_POSITIVE_NUMBER("REQUIRED_POSITIVE_NUMBER", 120, "{PREFIX}&cA positive number is required!", "Required-Positive-Number"), 
    TARGET_A_BLOCK("TARGET_A_BLOCK", 121, "{PREFIX}&cYou must target a block!", "Target-A-Block"), 
    TARGET_A_PLAYER("TARGET_A_PLAYER", 122, "{PREFIX}&cYou must target a player!", "Target-A-Player"), 
    VALUE_BETWEEN_ONE_TO_FIVE("VALUE_BETWEEN_ONE_TO_FIVE", 123, "{PREFIX}&cQuality value is between 1 to 5!", (String)null), 
    REMOVE_ITEM_FROM_SLOT_TO_EQUIP_GADGET("REMOVE_ITEM_FROM_SLOT_TO_EQUIP_GADGET", 124, "{PREFIX}&cYou must remove your item in slot {SLOT}(&b{ITEM}&c) to equip gadget!", "Remove-Item-From-Slot-To-Equip-Gadget"), 
    REMOVE_ITEM_FROM_SLOT_TO_EQUIP_MORPH("REMOVE_ITEM_FROM_SLOT_TO_EQUIP_MORPH", 125, "{PREFIX}&cYou must remove your item in slot {SLOT}(&b{ITEM}&c) to equip morph!", "Remove-Item-From-Slot-To-Equip-Morph"), 
    REMOVE_ITEM_FROM_SLOT_TO_EQUIP_EMOTE("REMOVE_ITEM_FROM_SLOT_TO_EQUIP_EMOTE", 126, "{PREFIX}&cYou must remove your item in slot {SLOT}(&b{ITEM}&c) to equip emote!", "Remove-Item-From-Slot-To-Equip-Emote"), 
    REMOVE_HELMET_TO_EQUIP_HAT("REMOVE_HELMET_TO_EQUIP_HAT", 127, "{PREFIX}&cYou must remove your helmet to equip hat!", "Remove-Helmet-To-Equip-Hat"), 
    REMOVE_HELMET_TO_EQUIP_ANIMATED_HAT("REMOVE_HELMET_TO_EQUIP_ANIMATED_HAT", 128, "{PREFIX}&cYou must remove your helmet to equip animated hat!", "Remove-Helmet-To-Equip-Animated-Hat"), 
    REMOVE_HELMET_TO_EQUIP_BANNER("REMOVE_HELMET_TO_EQUIP_BANNER", 129, "{PREFIX}&cYou must remove your helmet to equip banner!", "Remove-Helmet-To-Equip-Banner"), 
    REMOVE_HELMET_TO_EQUIP_EMOTE("REMOVE_HELMET_TO_EQUIP_EMOTE", 130, "{PREFIX}&cYou must remove your helmet to equip emote!", "Remove-Helmet-To-Equip-Emote"), 
    REMOVE_ARMOR_TO_EQUIP_SUIT("REMOVE_ARMOR_TO_EQUIP_SUIT", 131, "{PREFIX}&cYou must remove your armor to equip suit!", "Remove-Armor-To-Equip-Suit"), 
    FAILED_TO_PURCHASE("FAILED_TO_PURCHASE", 132, "&cFailed to get your purchase item!", "Failed-To-Purchase"), 
    ITEM_UNPURCHASABLE("ITEM_UNPURCHASABLE", 133, "{PREFIX}&cYou can't purchase this item!", "Item-Unpurchasable"), 
    PLAYER_NOT_ENOUGH_MYSTERY_DUST("PLAYER_NOT_ENOUGH_MYSTERY_DUST", 134, "{PREFIX}&cYou only have &b{MYSTERY_DUST} &cmystery dust!", "Player-Not-Enough-MysteryDust"), 
    PLAYER_ADDED_MYSTERY_DUST("PLAYER_ADDED_MYSTERY_DUST", 135, "{PREFIX}&eYou've successfully added &b{MYSTERY_DUST} &emystery dust to &b{PLAYER}&e.", "Added-MysteryDust"), 
    PLAYER_ADDED_MYSTERY_DUST_TO_ONLINE_PLAYERS("PLAYER_ADDED_MYSTERY_DUST_TO_ONLINE_PLAYERS", 136, "{PREFIX}&eYou've successfully added &b{MYSTERY_DUST} &emystery dust to &b{ONLINE} &eplayer(s).", "Added-MysteryDust-To-All-Players"), 
    PLAYER_CHECK_MYSTERY_DUST("PLAYER_CHECK_MYSTERY_DUST", 137, "&e{PLAYER} have &b{MYSTERY_DUST} &eMystery Dust.", "Check-MysteryDust"), 
    PLAYER_RECEIVED_MYSTERY_DUST("PLAYER_RECEIVED_MYSTERY_DUST", 138, "{PREFIX}&eYou've received &b{MYSTERY_DUST} &emystery dust from &b{PLAYER}&e.", "Received-MysteryDust"), 
    PLAYER_REMOVED_MYSTERY_DUST("PLAYER_REMOVED_MYSTERY_DUST", 139, "{PREFIX}&eYou've removed &b{MYSTERY_DUST} &emystery dust from &b{PLAYER}&e.", "Removed-MysteryDust"), 
    PLAYER_SENT_MYSTERY_DUST("PLAYER_SENT_MYSTERY_DUST", 140, "{PREFIX}&eYou've sent &b{MYSTERY_DUST} &emystery dust to &b{PLAYER}&e.", "Sent-MysteryDust"), 
    PLAYER_SET_MYSTERY_DUST("PLAYER_SET_MYSTERY_DUST", 141, "{PREFIX}&eYou've set &b{MYSTERY_DUST} &emystery dust for &b{PLAYER}&e.", "Set-MysteryDust"), 
    PLAYER_ONLY_HAVE_MYSTERY_DUST("PLAYER_ONLY_HAVE_MYSTERY_DUST", 142, "{PREFIX}&b{PLAYER} &conly have &b{MYSTERY_DUST} &cmystery dust!", "Only-Have-MysteryDust"), 
    REMOVED_MYSTERY_DUST_FROM_PLAYER("REMOVED_MYSTERY_DUST_FROM_PLAYER", 143, "{PREFIX}&b{MYSTERY_DUST} &emystery dust has been removed from your account.", "Removed-MysteryDust-From-Player"), 
    SET_PLAYER_MYSTERY_DUST("SET_PLAYER_MYSTERY_DUST", 144, "{PREFIX}&eYour mystery dust have been set to &b{MYSTERY_DUST}&e.", "Set-Player-MysteryDust"), 
    NOT_ENOUGH_MYSTERY_DUST_TO_PURCHASE("NOT_ENOUGH_MYSTERY_DUST_TO_PURCHASE", 145, "{PREFIX}&cSorry, you don't have enough mystery dust to purchase this item!", "Not-Enough-MysteryDust-To-Purchase"), 
    PAY_MYSTERY_DUST_TO_SELF("PAY_MYSTERY_DUST_TO_SELF", 146, "{PREFIX}&cYou can't pay mystery dust to yourself!", "Pay-MysteryDust-To-Self"), 
    FAILED_TO_DEDUCT_MYSTERY_DUST("FAILED_TO_DEDUCT_MYSTERY_DUST", 147, "{PREFIX}&cFailed to deduct your mystery dust. Please try again.", "Failed-To-Deduct-Mystery-Dust"), 
    PLAYER_GAVE_MYSTERY_BOXES("PLAYER_GAVE_MYSTERY_BOXES", 148, "{PREFIX}&eYou've successfully gave &b{MYSTERY_BOXES} mystery boxes &eto &b{PLAYER}&e.", "Gave-Mystery-Boxes"), 
    PLAYER_GAVE_MYSTERY_BOXES_TO_ALL_PLAYERS("PLAYER_GAVE_MYSTERY_BOXES_TO_ALL_PLAYERS", 149, "{PREFIX}&eYou've successfully gave &b{MYSTERY_BOXES} mystery boxes &eto &b{ONLINE} &eplayer(s).", "Gave-Mystery-Boxes-To-All-Players"), 
    PLAYER_RECEIVED_MYSTERY_BOXES("PLAYER_RECEIVED_MYSTERY_BOXES", 150, "{PREFIX}&eYou've received &b{MYSTERY_BOXES} mystery boxes &efrom &b{PLAYER}&e.", "Received-Mystery-Boxes"), 
    ADDED_A_MYSTERY_VAULT("ADDED_A_MYSTERY_VAULT", 151, "{PREFIX}&aSuccessful create Mystery Vault &f'{NAME}'&a.", "Added-Mystery-Vault"), 
    REDEFINED_A_MYSTERY_VAULT("REDEFINED_A_MYSTERY_VAULT", 152, "{PREFIX}&aThe location of mystery vault &f'{NAME}' &ahas been redefined.", "Redefined-Mystery-Vault"), 
    MYSTERY_VAULT_SAME_LOCATION("MYSTERY_VAULT_SAME_LOCATION", 153, "{PREFIX}&cYou have already created mystery vault at this location!", "Mystery-Vault-Same-Location"), 
    MYSTERY_VAULT_IS_EXISTS("MYSTERY_VAULT_IS_EXISTS", 154, "{PREFIX}&cMystery Vault with that name already exists!", "Mystery-Vault-Is-Exists"), 
    DO_NOT_HAVE_ANY_MYSTERY_VAULT("DO_NOT_HAVE_ANY_MYSTERY_VAULT", 155, "{PREFIX}&cYou do not have any Mystery Vault created!", "Do-Not-Have-Any-Mystery-Vault"), 
    NO_MYSTERY_VAULT_NEARBY("NO_MYSTERY_VAULT_NEARBY", 156, "{PREFIX}&cThere is no Mystery Vault in the given radius!", "No-Mystery-Vault-Nearby"), 
    REMOVED_MYSTERY_VAULT("REMOVED_MYSTERY_VAULT", 157, "{PREFIX}&aSuccessfully removed the Mystery Vault &f'{NAME}'&a.", "Removed-Mystery-Vault"), 
    MYSTERY_VAULT_NOT_FOUND("MYSTERY_VAULT_NOT_FOUND", 158, "{PREFIX}&cCan't find any Mystery Vault at this location!", "Mystery-Vault-Not-Found"), 
    MYSTERY_VAULT_NOT_FOUND_WITH_NAME("MYSTERY_VAULT_NOT_FOUND_WITH_NAME", 159, "{PREFIX}&cCan't find a Mystery Vault named &f'{NAME}'&c!", "Mystery-Vault-Not-Found-With-Name"), 
    TELEPORTED_TO_MYSTERY_VAULT("TELEPORTED_TO_MYSTERY_VAULT", 160, "{PREFIX}&eYou were teleported to the Mystery Vault named &f'{NAME}'&e.", "Teleport-To-Mystery-Vault"), 
    OPEN_MYSTERY_VAULT_AT_A_TIME("OPEN_MYSTERY_VAULT_AT_A_TIME", 161, "{PREFIX}&cOnly one player can use the Mystery Vault at a time!", "Open-Mystery-Vault-At-A-Time"), 
    CAN_ONLY_OPEN_ONE_MYSTERY_BOX("CAN_ONLY_OPEN_ONE_MYSTERY_BOX", 162, "{PREFIX}&cWait for this box to finish opening first!", "Can-Only-Open-One-Mystery-Box"), 
    PURCHASE_CANCELLED("PURCHASE_CANCELLED", 163, "{PREFIX}&cPurchase cancelled!", "Purchase-Cancelled"), 
    MYSTERY_BOXES_ARE_DISABLED("MYSTERY_BOXES_ARE_DISABLED", 164, "{PREFIX}&cMystery Boxes are disabled!", "Mystery-Boxes-Are-Disabled"), 
    CRAFTED_MYSTERY_BOX("CRAFTED_MYSTERY_BOX", 165, "&aYou crafted &b{NAME}&a.", "Crafted-Mystery-Box"), 
    PLAYER_GAVE_MYSTERY_GIFTS("PLAYER_GAVE_MYSTERY_GIFTS", 166, "{PREFIX}&eYou've successfully gave &b{GIFTS} &emystery gift packs&e to &r{PLAYER}&e.", "Gave-Mystery-Gifts"), 
    PLAYER_RECEIVED_MYSTERY_GIFTS("PLAYER_RECEIVED_MYSTERY_GIFTS", 167, "{PREFIX}&eYou've received &b{GIFTS} &emystery gift packs&e from &r{PLAYER}&e.", "Received-Mystery-Gifts"), 
    SEND_A_GIFT_TO_PLAYER("SEND_A_GIFT_TO_PLAYER", 168, "&aYou send a gift contaning &b5 Mystery Boxes &ato &r{PLAYER}&a!", "Send-A-Gift-To-Player"), 
    RECEIVED_GIFT("RECEIVED_GIFT", 169, "&aYou received a gift from &r{PLAYER}&a! Visit a &bMystery Vault &ato open it!", "Received-Gift"), 
    MYSTERY_BOX_WAS_EXPIRED("MYSTERY_BOX_WAS_EXPIRED", 170, "{PREFIX}&cThis mystery box was expired. Please open your mystery box before it's expired.", "Mystery-Box-Was-Expired"), 
    PLAYER_CHECK_MYSTERY_BOXES("PLAYER_CHECK_MYSTERY_BOXES", 171, "&e{PLAYER} have &b{MYSTERY_BOXES} &eMystery Boxes.", "Check-Mystery-Boxes"), 
    SELECT_MYSTERY_VAULT_ANIMATION("SELECT_MYSTERY_VAULT_ANIMATION", 172, "&eYou selected &b{ANIMATION} &efor your mystery vault animation.", "Select-Mystery-Vault-Animation"), 
    NOT_ENOUGH_MYSTERY_BOXES("NOT_ENOUGH_MYSTERY_BOXES", 173, "&cYou do not have enough mystery boxes can be opened.", "Not-Enough-Mystery-Boxes"), 
    COUNTING_MYSTERY_BOXES("COUNTING_MYSTERY_BOXES", 174, "&cCounting Mystery Boxes...", "Counting-Mystery-Boxes"), 
    NO_PERMISSION_TO_OPEN_ONE_STAR_MYSTERY_BOX("NO_PERMISSION_TO_OPEN_ONE_STAR_MYSTERY_BOX", 175, "{PREFIX}&cYou don't have the required permission to open this box!", "No-Permission-To-Open-One-Star-Box"), 
    NO_PERMISSION_TO_OPEN_TWO_STAR_MYSTERY_BOX("NO_PERMISSION_TO_OPEN_TWO_STAR_MYSTERY_BOX", 176, "{PREFIX}&cYou don't have the required permission to open this box!", "No-Permission-To-Open-Two-Star-Box"), 
    NO_PERMISSION_TO_OPEN_THREE_STAR_MYSTERY_BOX("NO_PERMISSION_TO_OPEN_THREE_STAR_MYSTERY_BOX", 177, "{PREFIX}&cYou don't have the required permission to open this box!", "No-Permission-To-Open-Three-Star-Box"), 
    NO_PERMISSION_TO_OPEN_FOUR_STAR_MYSTERY_BOX("NO_PERMISSION_TO_OPEN_FOUR_STAR_MYSTERY_BOX", 178, "{PREFIX}&cYou don't have the required permission to open this box!", "No-Permission-To-Open-Four-Star-Box"), 
    NO_PERMISSION_TO_OPEN_FIVE_STAR_MYSTERY_BOX("NO_PERMISSION_TO_OPEN_FIVE_STAR_MYSTERY_BOX", 179, "{PREFIX}&cYou don't have the required permission to open this box!", "No-Permission-To-Open-Five-Star-Box"), 
    PURCHASED_ANIMATED_HAT("PURCHASED_ANIMATED_HAT", 180, "&eYou purchased {ITEM}&e.", "Item-Purchase-Messages.Purchase-Animated-Hat"), 
    PURCHASED_BANNER("PURCHASED_BANNER", 181, "&eYou purchased {ITEM}&e.", "Item-Purchase-Messages.Purchase-Banner"), 
    PURCHASED_CLOAK("PURCHASED_CLOAK", 182, "&eYou purchased {ITEM}&e.", "Item-Purchase-Messages.Purchase-Cloak"), 
    PURCHASED_EMOTE("PURCHASED_EMOTE", 183, "&eYou purchased {ITEM}&e.", "Item-Purchase-Messages.Purchase-Emote"), 
    PURCHASED_GADGET("PURCHASED_GADGET", 184, "&eYou purchased {ITEM}&e.", "Item-Purchase-Messages.Purchase-Gadget"), 
    PURCHASED_HAT("PURCHASED_HAT", 185, "&eYou purchased {ITEM}&e.", "Item-Purchase-Messages.Purchase-Hat"), 
    PURCHASED_MINIATURE("PURCHASED_MINIATURE", 186, "&eYou purchased {ITEM}&e.", "Item-Purchase-Messages.Purchase-Miniature"), 
    PURCHASED_MORPH("PURCHASED_MORPH", 187, "&eYou purchased {ITEM}&e.", "Item-Purchase-Messages.Purchase-Morph"), 
    PURCHASED_PARTICLE("PURCHASED_PARTICLE", 188, "&eYou purchased {ITEM}&e.", "Item-Purchase-Messages.Purchase-Particle"), 
    PURCHASED_PET("PURCHASED_PET", 189, "&eYou purchased {ITEM}&e.", "Item-Purchase-Messages.Purchase-Pet"), 
    PURCHASED_SUIT("PURCHASED_SUIT", 190, "&eYou purchased {ITEM}&e.", "Item-Purchase-Messages.Purchase-Suit"), 
    EMOTE_IS_ACTIVATED("EMOTE_IS_ACTIVATED", 191, "{PREFIX}&cEmote is already active!", "Emote-Is-Activated"), 
    GADGET_IS_ACTIVATED("GADGET_IS_ACTIVATED", 192, "{PREFIX}&c{GADGET} is already active!", "Gadget-Is-Activated"), 
    MORPH_SKILL_IS_ACTIVATED("MORPH_SKILL_IS_ACTIVATED", 193, "{PREFIX}&c{MORPH} skill is already active!", "Morph-Skill-Is-Activated"), 
    SUIT_ABILITY_IS_ACTIVATED("SUIT_ABILITY_IS_ACTIVATED", 194, "{PREFIX}&c{SUIT} ability is already active!", "Suit-Ability-Is-Activated"), 
    MORPH_ABILITY_IS_DISABLED("MORPH_ABILITY_IS_DISABLED", 195, "{PREFIX}&c{MORPH} ability is currently disabled!", "Morph-Ability-Is-Disabled"), 
    IS_NOT_MORPHED("IS_NOT_MORPHED", 196, "&cYou're not currently morphed!", "Is-Not-Morphed"), 
    NO_PET_SPAWNED("NO_PET_SPAWNED", 197, "{PREFIX}&cYou don't currently have a pet spawned!", "No-Pet-Spawned"), 
    UNLOCK_PET_BEFORE_RENAME("UNLOCK_PET_BEFORE_RENAME", 198, "&c{PLAYER} needed to unlock {TYPE} pet before you can rename it.", "Unlock-Pet-Before-Rename"), 
    PET_NAME_IN_BLACKLIST("PET_NAME_IN_BLACKLIST", 199, "&cYou're not allowed to set the pet to this name as it contains indecent text.", "Pet-Name-In-Blacklist"), 
    RENAME_PET("RENAME_PET", 200, "&eSet your {TYPE} pet's name to &a{NAME}&e.", "Rename-Pet"), 
    RENAME_PET_FOR_PLAYER("RENAME_PET_FOR_PLAYER", 201, "&e{PLAYER} {TYPE} pet's name has been set to &a{NAME}&e.", "Rename-Pet-For-Player"), 
    RENAME_PET_IN_CHAT("RENAME_PET_IN_CHAT", 202, "&eYou have &c20 &eseconds to type your pet's name, please insert your pet's name in the chat.\n&eType &2Cancel &eto cancel renaming your pet.", "Rename-Pet-In-Chat"), 
    NO_PERMISSION_TO_RIDE_PET("NO_PERMISSION_TO_RIDE_PET", 203, "&cYou do not have the permission to ride pet!", "No-Permission-To-Ride-Pet"), 
    NOT_ALLOWED_TO_RIDE_OTHER_PET("NOT_ALLOWED_TO_RIDE_OTHER_PET", 204, "&cYou cannot ride other people's pets!", "Not-Allowed-To-Ride-Other-Pet"), 
    TIMED_OUT("TIMED_OUT", 205, "&cRename pet time is over, you haven't changed your pet's name!", "Timed-Out"), 
    CANCEL_RENAME_PET("CANCEL_RENAME_PET", 206, "&cCancelled renaming of your pet.", "Cancel-Rename-Pet"), 
    REQUEST_PET_WITH_HAPPY_STATUS("REQUEST_PET_WITH_HAPPY_STATUS", 207, "&cYou must have at least one pet with a Happy status in order to do that.", "Request-Pet-With-Happy-Status"), 
    CLICK_TO_INCREASE_HAPPINESS("CLICK_TO_INCREASE_HAPPINESS", 208, "&bRight-Click &eyour pets inside the Pets Menu to feed them and to increase their happiness.", "Click-To-Increase-Happiness"), 
    PET_EARN_EXP("PET_EARN_EXP", 209, "&eYour {LEVEL} {PET_NAME} &eearned &b{EXP} EXP &efrom the pet mission!", "Pet-Earn-EXP"), 
    PET_LEVEL_UP("PET_LEVEL_UP", 210, "&eYour {LEVEL} {PET_NAME} &eearned &b{EXP} EXP &efrom the pet mission! It leveled up.", "Pet-Level-Up"), 
    SEND_PET_FOR_MISSION_IS_ON_COOLDOWN("SEND_PET_FOR_MISSION_IS_ON_COOLDOWN", 211, "&cThis is currently on cooldown. Please wait {COOLDOWN_MINUTES} more minutes.", "Send-Pet-For-Mission-Is-On-Cooldown"), 
    NO_PERMISSION_TO_SUMMON_PET("NO_PERMISSION_TO_SUMMON_PET", 212, "&cYou don't have the permission to summon your pets!", "No-Permission-To-Spawn-Pet"), 
    PET_STAT_FULLED("PET_STAT_FULLED", 213, "&cYour {PET_NAME} &c{STAT} is already full!", "Pet-Stat-Fulled"), 
    ZERO_PET_ITEM_REMAIN("ZERO_PET_ITEM_REMAIN", 214, "&cThis item can be found through the &bMystery Vault&c!", "Zero-Pet-Item-Remain"), 
    ATE_FOOD_AND_DONT_LIKE_IT("ATE_FOOD_AND_DONT_LIKE_IT", 215, "&eYour {PET_NAME} &eate a &a{ITEM}&e. They don't like it very much. (&a+{INCREMENT} &bHunger&e)", "Ate-Food-And-Dont-Like-It"), 
    ATE_FOOD_AND_LIKE_IT("ATE_FOOD_AND_LIKE_IT", 216, "&eYour {PET_NAME} &eate a &a{ITEM}&e. They like it! (&a+{INCREMENT} &bHunger&e)", "Ate-Food-And-Like-It"), 
    ATE_FOOD_AND_REALLY_LIKE_IT("ATE_FOOD_AND_REALLY_LIKE_IT", 217, "&eYour {PET_NAME} &eate a &a{ITEM}&e. They really like it! (&a+{INCREMENT} &bHunger&e)", "Ate-Food-And-Really-Like-It"), 
    ATE_FAVOURITE_FOOD("ATE_FAVOURITE_FOOD", 218, "&eYour {PET_NAME} &eate a &a{ITEM}&e. It's their favourite food! (&a+{INCREMENT} &bHunger&e)", "Ate-Favourite-Food"), 
    DRANK_DRINK_AND_DONT_LIKE_IT("DRANK_DRINK_AND_DONT_LIKE_IT", 219, "&eYour {PET_NAME} &edrank a &a{ITEM}&e. They don't like it very much. (&a+{INCREMENT} &bThirst&e)", "Drank-Drink-And-Dont-Like-It"), 
    DRANK_DRINK_AND_LIKE_IT("DRANK_DRINK_AND_LIKE_IT", 220, "&eYour {PET_NAME} &edrank a &a{ITEM}&e. They like it! (&a+{INCREMENT} &bThirst&e)", "Drank-Drink-And-Like-It"), 
    DRANK_DRINK_AND_REALLY_LIKE_IT("DRANK_DRINK_AND_REALLY_LIKE_IT", 221, "&eYour {PET_NAME} &edrank a &a{ITEM}&e. They really like it! (&a+{INCREMENT} &bThirst&e)", "Drank-Drink-And-Really-Like-It"), 
    DRANK_FAVOURITE_DRINK("DRANK_FAVOURITE_DRINK", 222, "&eYour {PET_NAME} &edrank a &a{ITEM}&e. It's their favourite drink! (&a+{INCREMENT} &bThirst&e)", "Drank-Favourite-Drink"), 
    PLAYED_TOY_AND_DONT_LIKE_IT("PLAYED_TOY_AND_DONT_LIKE_IT", 223, "&eYour {PET_NAME} &eplayed with a &a{ITEM}&e. They don't like it very much. (&a+{INCREMENT} &bExercise&e)", "Played-Toy-And-Dont-Like-It"), 
    PLAYED_TOY_AND_LIKE_IT("PLAYED_TOY_AND_LIKE_IT", 224, "&eYour {PET_NAME} &eplayed with a &a{ITEM}&e. They like it! (&a+{INCREMENT} &bExercise&e)", "Played-Toy-And-Like-It"), 
    PLAYED_TOY_AND_REALLY_LIKE_IT("PLAYED_TOY_AND_REALLY_LIKE_IT", 225, "&eYour {PET_NAME} &eplayed with a &a{ITEM}&e. They really like it! (&a+{INCREMENT} &bExercise&e)", "Played-Toy-And-Really-Like-It"), 
    PLAYED_FAVOURITE_TOY("PLAYED_FAVOURITE_TOY", 226, "&eYour {PET_NAME} &eplayed with a &a{ITEM}&e. It's their favourite toy! (&a+{INCREMENT} &bExercise&e)", "Played-Favourite-Toy"), 
    PLAYER_ADDED_PET_ITEM("PLAYER_ADDED_PET_ITEM", 227, "{PREFIX}&eYou've successfully added &b{AMOUNT} &e{PET_ITEM} &epet item to &b{PLAYER}&e.", "Added-Pet-Item"), 
    PLAYER_RECEIVED_PET_ITEM("PLAYER_RECEIVED_PET_ITEM", 228, "{PREFIX}&eYou've received &b{AMOUNT} &e{PET_ITEM} &epet item from &b{PLAYER}&e.", "Received-Pet-Item"), 
    PLAYER_REMOVED_PET_ITEM("PLAYER_REMOVED_PET_ITEM", 229, "{PREFIX}&eYou've removed &b{AMOUNT} &e{PET_ITEM} &epet item from &b{PLAYER}&e.", "Removed-Pet-Item"), 
    REMOVED_PET_ITEM_FROM_PLAYER("REMOVED_PET_ITEM_FROM_PLAYER", 230, "{PREFIX}&b{AMOUNT} &e{PET_ITEM} &ehas been removed from your pet items.", "Removed-Pet-Item-From-Player"), 
    PLAYER_SET_PET_ITEM("PLAYER_SET_PET_ITEM", 231, "{PREFIX}&eYou've set &b{AMOUNT} &e{PET_ITEM} &epet item for &b{PLAYER}&e.", "Set-Pet-Item"), 
    SET_PLAYER_PET_ITEM("SET_PLAYER_PET_ITEM", 232, "{PREFIX}&eYour &e{PET_ITEM} &epet item have been set to &b{AMOUNT}&e.", "Set-Player-Pet-Item"), 
    ROCKET_COUNTDOWN("ROCKET_COUNTDOWN", 233, "&c&lROCKET LAUNCH IN {TIMER} {SECOND}!", "Rocket-Countdown"), 
    ROCKET_LIFT_OFF("ROCKET_LIFT_OFF", 234, "&a&lWE HAVE LIFT OFF!", "Rocket-Lift-Off"), 
    ENABLED_SELF_MORPH_VIEW("ENABLED_SELF_MORPH_VIEW", 235, "{PREFIX}&eYou have enabled self view for morphs!", "Enabled-Self-Morph-View"), 
    DISABLED_SELF_MORPH_VIEW("DISABLED_SELF_MORPH_VIEW", 236, "{PREFIX}&eYou have disabled self view for morphs!", "Disabled-Self-Morph-View"), 
    ENABLED_BYPASS_COOLDOWN("ENABLED_BYPASS_COOLDOWN", 237, "{PREFIX}&eYou have enabled cooldown bypass.", "Enabled-Bypass-Cooldown"), 
    DISABLED_BYPASS_COOLDOWN("DISABLED_BYPASS_COOLDOWN", 238, "{PREFIX}&eYou have disabled cooldown bypass.", "Disabled-Bypass-Cooldown"), 
    ENABLED_RANDOM_MYSTERY_VAULT_ANIMATION("ENABLED_RANDOM_MYSTERY_VAULT_ANIMATION", 239, "{PREFIX}&eYou &aenabled &bRandom Animation &efor your mystery vault animation.", "Enabled-Random-Mystery-Vault-Animation"), 
    DISABLED_RANDOM_MYSTERY_VAULT_ANIMATION("DISABLED_RANDOM_MYSTERY_VAULT_ANIMATION", 240, "{PREFIX}&eYou &cdisabled &bRandom Animation &efor your mystery vault animation.", "Disabled-Random-Mystery-Vault-Animation"), 
    DISABLED_COMMAND_WHILE_COSMETICS_ACTIVATED("DISABLED_COMMAND_WHILE_COSMETICS_ACTIVATED", 241, "{PREFIX}&cYou can't use this command while cosmetics are activated!", "Disabled-Command-While-Cosmetics-Activated"), 
    INVALID_TYPE("INVALID_TYPE", 242, "{PREFIX}&cThis {TYPE} that you entered is invalid!", "Invalid-Type"), 
    TYPE_IS_NOT_ENABLED("TYPE_IS_NOT_ENABLED", 243, "{PREFIX}&cThis {TYPE} is not enabled!", "Type-Is-Not-Enabled"), 
    TURN_OFF_BUMBLEBEE_SONG("TURN_OFF_BUMBLEBEE_SONG", 244, "{PREFIX}&cBumblebee song has been turned off!", "Turn-Off-Bumblebee-Song"), 
    PLAYING_SONG("PLAYING_SONG", 245, "{RANDOM_COLOR}Now playing: {SONG}", "Playing-Song"), 
    ONLY_BOOLEAN_VALUE_CAN_BE_ACCEPTED("ONLY_BOOLEAN_VALUE_CAN_BE_ACCEPTED", 246, "&cOnly boolean value can be accepted!", "Only-Boolean-Value-Can-Be-Accepted"), 
    REQUIRED_TIME_FORMAT("REQUIRED_TIME_FORMAT", 247, "{PREFIX}&cPlease fill in the correct time format! ('h' for hours,'d' for days, 'm' for months).", "Required-Time-Format"), 
    REQUIRED_FULL_DATA("REQUIRED_FULL_DATA", 248, "{PREFIX}&cPlease make sure your data is not missing.", "Required-Full-Data"), 
    SAME_TYPE_GADGET_ACTIVATED("SAME_TYPE_GADGET_ACTIVATED", 249, "{PREFIX}&cThere's already have a {GADGET} activate! Please try again later.", "Already-Activate-One"), 
    GADGET_ACTIVATED_IN_SAME_AREA("GADGET_ACTIVATED_IN_SAME_AREA", 250, "{PREFIX}&cThere's a gadget activated in this area! Please try at another area.", "Gadget-Activated-In-Same-Area"), 
    ENABLED("ENABLED", 251, "&aEnabled", "Enabled"), 
    DISABLED("DISABLED", 252, "&cDisabled", "Disabled"), 
    COOLDOWN_BYPASS("COOLDOWN_BYPASS", 253, "Cooldown Bypass", "Cooldown-Bypass"), 
    SELF_MORPH_VIEW("SELF_MORPH_VIEW", 254, "Self Morph View", "Self-Morph-View"), 
    UNEQUIP_COSMETICS_DUE_TO_LOW_TPS("UNEQUIP_COSMETICS_DUE_TO_LOW_TPS", 255, "{PREFIX}&cYour cosmetics has been unequipped due to server lag.", "Unequip-Cosmetics-Due-To-Low-TPS"), 
    DISABLE_USAGE_OF_COSMETICS("DISABLE_USAGE_OF_COSMETICS", 256, "{PREFIX}&cSorry for the inconvenience, all cosmetics have been disabled due to server lag.", "Disable-Usage-Of-Cosmetics"), 
    NOT_ALLOW_COSMETICS_IN_REGION("NOT_ALLOW_COSMETICS_IN_REGION", 257, "{PREFIX}&cYou're not allowed to equip cosmetics in this region.", "Not-Allow-Cosmetics-In-Region"), 
    NOT_ALLOW_HAT_IN_REGION("NOT_ALLOW_HAT_IN_REGION", 258, "{PREFIX}&cYou're not allowed to equip hat in this region.", "Not-Allow-Hat-In-Region"), 
    NOT_ALLOW_ANIMATED_HAT_IN_REGION("NOT_ALLOW_ANIMATED_HAT_IN_REGION", 259, "{PREFIX}&cYou're not allowed to equip animated hat in this region.", "Not-Allow-Animated-Hat-In-Region"), 
    NOT_ALLOW_PARTICLE_IN_REGION("NOT_ALLOW_PARTICLE_IN_REGION", 260, "{PREFIX}&cYou're not allowed to equip particle in this region.", "Not-Allow-Particle-In-Region"), 
    NOT_ALLOW_SUIT_IN_REGION("NOT_ALLOW_SUIT_IN_REGION", 261, "{PREFIX}&cYou're not allowed to equip suit in this region.", "Not-Allow-Suit-In-Region"), 
    NOT_ALLOW_GADGET_IN_REGION("NOT_ALLOW_GADGET_IN_REGION", 262, "{PREFIX}&cYou're not allowed to equip gadget in this region.", "Not-Allow-Gadget-In-Region"), 
    NOT_ALLOW_PET_IN_REGION("NOT_ALLOW_PET_IN_REGION", 263, "{PREFIX}&cYou're not allowed to equip pet in this region.", "Not-Allow-Pet-In-Region"), 
    NOT_ALLOW_MINIATURES_IN_REGION("NOT_ALLOW_MINIATURES_IN_REGION", 264, "{PREFIX}&cYou're not allowed to equip miniature in this region.", "Not-Allow-Miniature-In-Region"), 
    NOT_ALLOW_MORPH_IN_REGION("NOT_ALLOW_MORPH_IN_REGION", 265, "{PREFIX}&cYou're not allowed to morph in this region.", "Not-Allow-Morph-In-Region"), 
    NOT_ALLOW_BANNER_IN_REGION("NOT_ALLOW_BANNER_IN_REGION", 266, "{PREFIX}&cYou're not allowed to equip banner in this region.", "Not-Allow-Banner-In-Region"), 
    NOT_ALLOW_EMOTES_IN_REGION("NOT_ALLOW_EMOTES_IN_REGION", 267, "{PREFIX}&cYou're not allowed to equip emote in this region.", "Not-Allow-Emote-In-Region"), 
    NOT_ALLOW_CLOAK_IN_REGION("NOT_ALLOW_CLOAK_IN_REGION", 268, "{PREFIX}&cYou're not allowed to equip cloak in this region.", "Not-Allow-Cloak-In-Region"), 
    NOT_ALLOW_PET_RIDING_IN_REGION("NOT_ALLOW_PET_RIDING_IN_REGION", 269, "{PREFIX}&cYou're not allowed to ride your pet in this region.", "Not-Allow-Pet-Riding-In-Region"), 
    SECOND("SECOND", 270, "Second", "Second"), 
    SECONDS("SECONDS", 271, "Seconds", "Seconds"), 
    MINUTE("MINUTE", 272, "minute", "Minute"), 
    MINUTES("MINUTES", 273, "minutes", "Minutes"), 
    HOUR("HOUR", 274, "hour", "Hour"), 
    HOURS("HOURS", 275, "hours", "Hours"), 
    DAY("DAY", 276, "day", "Day"), 
    DAYS("DAYS", 277, "days", "Days"), 
    NO_COSMETIC_EQUIPPED("NO_COSMETIC_EQUIPPED", 278, "none", "No-Cosmetic-Equipped"), 
    NO_RECENT_LOOT_FOUND("NO_RECENT_LOOT_FOUND", 279, "none", "No-Recent-Loot-Found"), 
    LOADING("LOADING", 280, "&cLoading...", "Loading");
    
    private String defaultMessage;
    private String path;
    
    private MessageType(final String name, final int ordinal, final String defaultMessage, final String path) {
        this.defaultMessage = defaultMessage;
        this.path = path;
        if (this.path != null && this.getFileMesssage() == null) {
            FileManager.getMessagesFile().addDefault(this.path, this.getDefaultMessage());
        }
    }
    
    public String getDefaultMessage() {
        return this.defaultMessage;
    }
    
    public String getFileMesssage() {
        return FileManager.getMessagesFile().get(this.path);
    }
    
    public String getFormatMessage() {
        if (this.path == null) {
            return ChatUtil.format(this.getDefaultMessage().replace("{PREFIX}", CookieGadgets.getCookieGadgetsData().getPrefix()));
        }
        if (this.getFileMesssage() == null) {
            FileManager.getMessagesFile().addDefault(this.path, this.getDefaultMessage());
            return ChatUtil.format(this.getDefaultMessage().replace("{PREFIX}", CookieGadgets.getCookieGadgetsData().getPrefix()));
        }
        return ChatUtil.format(this.getFileMesssage().replace("{PREFIX}", CookieGadgets.getCookieGadgetsData().getPrefix()));
    }
    
    @Override
    public String toString() {
        return this.getDefaultMessage();
    }
}
